config/routes.rb
Rails.application.routes.draw do

  get '/' => 'homes#top'
  resources :books

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
  if @book.save
    flash[:notice] = "Book was successfully created"
    redirect_to book_path(@book.id)
  else
    @books = Book.all
    render :index
  end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
     book = Book.find(params[:id])
  if book.update(book_params)
    flash[:notice] = "Book was successfully created"
    redirect_to book_path(book.id)
  else
    @book = book
    render :edit

  end
  end

  def destroy
    book = Book.find(params[:id])
  if book.destroy
    flash[:notice] = "Book was successfully destroyed"
    redirect_to "/books"
  else
    @books = Book.all
    render :index
  end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1 class="edit">Editing Book</h1>
<% if @book.errors.any? %>
<div class="error">
 <h2 class="error-mes"><%= @book.errors.count %> errors prohibited this book from being saved:</h2>

 <ul>
     <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
     <% end %>
 </ul>
</div>
<% end %>


<%= form_with model: @book do |f| %>
<div class="form-box">
 <div class="field">
  <label for="form-name">Title</label>
 </div>
 <div class="field">
  <div class="form"><%= f.text_field :title %></div>
 </div>
</div>

<div class="form-box">
 <div class="field">
  <label for="form-name">Body</label>
 </div>
 <div class="field">
  <div class="form"><%= f.text_field :body %></div>
 </div>
</div>


<div class="action">
<p><%= f.submit 'Update Book',class:"btn" %></p>
</div>
<% end %>


<a><%= link_to "Show", book_path(@book.id)%></a>
|
<a href="/books">Back</a>

app/views/books/index.html.erb
<p class="notice">
    <%= flash[:notice] %>
</p>

<h1 class="i-heading">Books</h1>

<table>

<thead>
    <th><p class= "i-title">Title</p></th>
    <th><p class= "i-body">Body</p></th>
</thead>

<tbody>
    <% @books.each do |book| %>
  <tr>
    <td><span><%= book.title %></span></td>
    <td><span><%= book.body %></span></td>
    <td><span><%= link_to "Show", book_path(book.id) %></span></td>
    <td><span><%= link_to "Edit", edit_book_path(book) %></span></td>
    <td><span><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></span></td>
  </tr>
    <% end %>
</tbody>

</table>



<h2 class="i-newbook">New book</h2>
 <% if @book.errors.any? %>
<div class="error">
 <h2 class="error-mes"><%= @book.errors.count %> errors prohibited this book from being saved:</h2>

 <ul>
     <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
     <% end %>
 </ul>
</div>
<% end %>

 <%= form_with model: @book do |f| %>
<div class="form-box">
 <div class="field">
  <label for="form-name">Title</label>
 </div>
 <div class="field">
  <div class="form"><%= f.text_field :title %></div>
 </div>
</div>

<div class="form-box">
 <div class="field">
  <label for="form-name">Body</label>
 </div>
 <div class="field">
  <div class="form"><%= f.text_area :body %></div>
 </div>
</div>

 <p><%= f.submit 'Create Book',class:"btn" %></p>
 <% end %>

app/views/books/show.html.erb
<p class="notice">
    <%= flash[:notice] %>
</p>

<p class="show"><strong>Title:</strong>
<%= @book.title %></p>

<p class="show"><strong>Body:</strong>
<%= @book.body %></p>


<a><%= link_to "Edit", edit_book_path(@book.id)%></a>
|
<a href="/books">Back</a>

app/views/homes/top.html.erb
 <h1 class="top-h">ようこそ
   <strong>Bookers</strong>
     へ！</h1>

 <p class="top-p"><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>

 <p class="top-p">印象を共有し交換することができます</p>

 <p class="top-p"><a href="/books">start</a></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>